export const ADD_COMMAND_REQUEST = "ADD_COMMAND_REQUEST"
export const ADD_COMMAND_SUCCESS = "ADD_COMMAND_SUCCESS"
export const ADD_COMMAND_FAILED = "ADD_COMMAND_FAILED"

export const GET_MY_COMMAND_REQUEST = "GET_MY_COMMAND_REQUEST"
export const GET_MY_COMMAND_SUCCESS = "GET_MY_COMMAND_SUCCESS"
export const GET_MY_COMMAND_FAILED = "GET_MY_COMMAND_FAILED"
