export const ADD_PRODUCTS_REQUEST = "ADD_PRODUCTS_REQUEST"
export const ADD_PRODUCTS_SUCCESS = "ADD_PRODUCTS_SUCCESS"
export const ADD_PRODUCTS_FAILED = "ADD_PRODUCTS_FAILED"

export const GET_PRODUCTS_COUNT_REQUEST = "ADD_PRODUCTS_COUNT_REQUEST"
export const GET_PRODUCTS_COUNT_SUCCESS = "ADD_PRODUCTS_COUNT_SUCCESS"
export const GET_PRODUCTS_COUNT_FAILED = "ADD_PRODUCTS_COUNT_FAILED"

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";

export const GET_MY_PRODUCT_REQUEST = "GET_MY_PRODUCT_REQUEST"
export const GET_MY_PRODUCT_SUCCESS = "GET_MY_PRODUCT_SUCCESS"
export const GET_MY_PRODUCT_FAILED = "GET_MY_PRODUCT_FAILED" 

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAILED = "GET_PRODUCT_DETAILS_FAILED";
export const GET_PRODUCT_DETAILS_RESET = "GET_PRODUCT_DETAILS_RESET";


export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILED = "UPDATE_PRODUCT_FAILED";

export const SUCCESS = "SUCCESS";