export const ADD_PRODUCTS_REQUEST = "ADD_PRODUCTS_REQUEST"
export const ADD_PRODUCTS_SUCCESS = "ADD_PRODUCTS_SUCCESS"
export const ADD_PRODUCTS_FAILED = "ADD_PRODUCTS_FAILED"

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_MY_PRODUCT_REQUEST = "GET_MY_PRODUCT_REQUEST"
export const GET_MY_PRODUCT_SUCCESS = "GET_MY_PRODUCT_SUCCESS"
export const GET_MY_PRODUCT_FAILED = "GET_MY_PRODUCT_FAILED" 

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL";
export const GET_PRODUCT_DETAILS_RESET = "GET_PRODUCT_DETAILS_RESET";
